services:
  frontend:
      image: 996904209733.dkr.ecr.us-east-1.amazonaws.com/contact-app/frontend:${IMAGE_TAG}
      ports:
        - "80:80"
        - "443:443"
      restart: unless-stopped
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt:ro
      depends_on:
        -  backend 
  backend:
    image: 996904209733.dkr.ecr.us-east-1.amazonaws.com/contact-app/backend:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    expose:
      - "3006:3006"
    depends_on:
      -  mongodb
  mongodb:
    image: mongo:7.0
    volumes:
      - mongodb:/data/db
    restart: always

volumes:
   mongodb:

