name: Mern-app-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install backend dependencies
        working-directory: .
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm ci

      - name: Build the application
        working-directory: ./client
        run: npm run build




